---
title: "load data and libraries"
author: "anne"
date: "13 desember 2018"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data 
#### Plots/ environment
```{r}
library(readr)

# data_plots <- read_delim("rawdata/fielddata_plots_2020-04-02.csv",
#                          ";", escape_double = FALSE, col_types = cols(ID = col_character(), `Notes per site` = col_skip(), X36 = col_skip(), X39 = col_skip(), X41 = col_skip(), date = col_character(), notes = col_skip(), `notes loi` = col_skip()), na = "NA",
#                          trim_ws = TRUE)
# 
# data_plots <- read_delim("rawdata/fielddata_plots_2020_04_20.csv",
#                          ";", escape_double = FALSE, col_types = cols(ID = col_character(), date = col_character()), na = "NA",
#                          trim_ws = TRUE)
# 
# data_plots <- as.data.frame(data_plots)
head(data_plots)
# save(data_plots, file = "data_plots_2020_04_20.rda")
# write.csv(data_plots3,'data_plots3_2020_07_17.csv')

# data_plots4 <- read_delim("processdata/data_plots4_2020_08_18.csv",
#                          ";", escape_double = FALSE, col_types = cols(id = col_character(), date = col_character()), na = "NA",
#                          trim_ws = TRUE)
# data_plots4 <- as.data.frame(data_plots4)
# save(data_plots4, file = "data_plots4_2020_08_18.rda")



load("processdata/data_plots_2020_04_20.rda")
load("processdata/data_plots_2020_06_25.rda")
load("processdata/data_plots2_2020_06_29.rda") # Like data_plots, but inluding column with mean cover and sd (species)
load("processdata/data_plots2_reference_2020_06_29.rda") # Like data_plots2, but only reference plots
load("processdata/data_plots2_normal_2020_06_29.rda") # Like data_plots2, but only non-reference plots
load("processdata/data_plots2_normal_2020_07_02.rda") # Like data_plots2_normal, but plotnumb as factor

load("processdata/data_plots2_2020_07_17.rda") # Like data_plots, but inluding column with mean cover and sd (species cover)
load("processdata/data_plots2_reference_2020_07_17.rda") # Like data_plots2, but only reference plots
load("processdata/data_plots2_normal_2020_07_17.rda") # Like data_plots2, but only normal (non-reference) plots

load("processdata/data_plots3_2020_07_16.rda") # Like data_plots2, but species richness and diversity
load("processdata/data_plots3_2020_07_17.rda") # Like data_plots2, but species richness and diversity

load("processdata/data_plots4_2020_08_18.rda") # Like data_plots3, with restoration year and new site and plot columns
load("processdata/data_full_2020_08_19.rda")
load("processdata/data_full_2020_08_24.rda") # including region

```


#### Species/ cover
```{r}
library(readr)

# data_species <- read_delim("rawdata/fielddata_species_2020_04_02.csv",
#                            ";", escape_double = FALSE, col_types = cols(ID = col_character(), X4 = col_skip(), X6 = col_skip(), note = col_skip(), species_per_plot = col_skip(), usikker = col_skip()), na = "NA", trim_ws = TRUE)

# data_species <- read_delim("rawdata/fielddata_species_2020_04_20.csv",
#                            ";", escape_double = FALSE, col_types = cols(ID = col_character()), na = "NA", trim_ws = TRUE)
# 
# data_species <- as.data.frame(data_species)
# head(data_species)
# save(data_species, file = "data_species_2020_06_25.rda")
# write.csv(data_species_wide3_sites,'data_species_wide3_sites.csv')
# write.csv(data_species_wide3,'data_species_wide3.csv')

# data_species_wide4 <- read_delim("processdata/data_species4_2020_08_18.csv",
#                            ";", escape_double = FALSE, col_types = cols(id = col_character()), na = "NA", trim_ws = TRUE)
# data_species_wide4 <- as.data.frame(data_species_wide4)
# save(data_species_wide4, file = "data_species4_2020_08_18.rda")




load("processdata/data_species_2020_04_20.rda")

load("processdata/data_species_wide_2020_04_20.rda")
load("processdata/data_species_wide_2020_06_25.rda")
load("processdata/data_species_wide_2020_06_26.rda")


load("processdata/data_species_wide2_2020_06_26.rda") # Includes mean and sd of species for rows and columns

# Includes columns with mean and sd for species cover, species richness measures and species diversity measures:
load("processdata/data_species_wide3_2020_07_15.rda")
# Includes columns with mean and sd for species cover, species richness measures and species diversity measures; grouped by site id:
load("processdata/data_species_wide3_sites_2020_07_15.rda")

# like data_species_wide3, with new site and plot columns:
load("processdata/data_species4_2020_08_18.rda")

head(data_species_wide)

```


























