---
title: "06_models_species_diversity"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## ------------- head data ----------------
```{r}

head(data_plots3)

```


## ----------- Test for data distribution/ screwness ---------
```{r}
library(fitdistrplus)

descdist(data_plots3$shannon, discrete = FALSE, boot = 500) # Normal, maybe lognormal
descdist(data_plots3$simpson, discrete = FALSE, boot = 500) # beta
descdist(data_plots3$sr_margalef, discrete = FALSE, boot = 500) # beta, maybe normal
descdist(data_plots3$sr_menhinick, discrete = FALSE, boot = 500) # lognormal

```


## correlation
```{r}
cor_df <- data.frame(data_plots3$bare_soil_c, data_plots3$dist_int_veg, data_plots3$field_layer_c, data_plots3$shrub_layer_c, data_plots3$tree_layer_c, data_plots3$caco, data_plots3$slope, data_plots3$loi, data_plots3$mean_cover, data_plots3$sd_cover, data_plots3$total_cover_layers, data_plots3$shannon, data_plots3$simpson, data_plots3$sr_margalef, data_plots3$sr_menhinick)

res <- cor(cor_df)

library(Hmisc)
library(corrplot)
corrplot(res)

```






## -------------------- Linear mixed model with "shannon" as response (all plots) -------------------

```{r}
library(lme4)
library(lmerTest)

#### random factor selection ----
lm0_rand <- lmer(shannon ~ dist_int_veg + total_cover_layers + field_layer_h + caco + slope + exposure + grain_size_stand_f + loi + method + site_type + year + (1|site_id/plot_id), data = data_plots3, REML = F) # Error: number of levels of each grouping factor must be < number of observations (problems: plotnumb:siteID)

lm1_rand <- lmer(shannon ~ dist_int_veg + total_cover_layers + field_layer_h + caco + slope + exposure + grain_size_stand_f + loi + method + site_type + year + (1|site_id), data = data_plots3, REML = F) #1

lm2_rand <- lmer(shannon ~ dist_int_veg + total_cover_layers + field_layer_h + caco + slope + exposure + grain_size_stand_f + loi + method + site_type + year +(1|plot_id), data = data_plots3, REML = F)



#### models ----
lm0 <- lmer(shannon ~ dist_int_veg + total_cover_layers + field_layer_h + caco + slope + exposure + grain_size_stand_f + loi + method + (1|site_id), data = data_plots3, REML = F)
lm0a <- lmer(shannon ~ dist_int_veg + total_cover_layers + field_layer_h + caco + slope + exposure + grain_size_stand_f + loi + year + (1|site_id), data = data_plots3, REML = F) # Warning: fixed-effect model matrix is rank deficient so dropping 1 column / coefficient ---> But why does it always drop year??

lm1 <- lmer(shannon ~ dist_int_veg + total_cover_layers  + caco + exposure + grain_size_stand_f + (1|site_id), data = data_plots3, REML = F)
lm2 <- lmer(shannon ~ dist_int_veg + total_cover_layers  + caco + grain_size_stand_f + (1|site_id), data = data_plots3, REML = F) 
lm3 <- lmer(shannon ~ dist_int_veg + total_cover_layers  + caco + exposure + (1|site_id), data = data_plots3, REML = F)

lm4 <- lmer(shannon ~ log(dist_int_veg+1) + total_cover_layers  + caco + grain_size_stand_f + (1|site_id), data = data_plots3, REML = F) #1
lm4_reml <- lmer(shannon ~ log(dist_int_veg+1) + total_cover_layers  + caco + grain_size_stand_f + (1|site_id), data = data_plots3, REML = T) #1

```



#### random factor selection
```{r}
library(lmerTest)
AIC(lm1_rand, lm2_rand)
#          df      AIC
# lm1_rand 23 275.2039
# lm2_rand 23 282.9316

```



#### model selection 
```{r}
drop1(lm0)

s <- step(lm0)
plot(s)

library(AICcmodavg)
AIC(lm2, lm4)

Cand.models <- list( )
Cand.models[[1]] <- lmer(shannon ~ dist_int_veg + total_cover_layers + field_layer_h + caco + slope + exposure + grain_size_stand_f + loi + method + (1|site_id), data = data_plots3, REML = F)
Cand.models[[2]] <- lmer(shannon ~ dist_int_veg + total_cover_layers  + caco + exposure + grain_size_stand_f + (1|site_id), data = data_plots3, REML = F)
Cand.models[[3]] <- lmer(shannon ~ dist_int_veg + total_cover_layers  + caco + grain_size_stand_f + (1|site_id), data = data_plots3, REML = F)
Cand.models[[4]] <- lmer(shannon ~ dist_int_veg + total_cover_layers  + caco + exposure + (1|site_id), data = data_plots3, REML = F)


aictab(Cand.models, second.ord = F) 
# Model selection based on AIC:
# 
#       K    AIC Delta_AIC AICWt Cum.Wt      LL
# Mod3 10 266.00      0.00  0.96   0.96 -123.00
# Mod2 18 273.61      7.61  0.02   0.99 -118.80
# Mod1 23 275.20      9.21  0.01   1.00 -114.60
# Mod4 14 276.75     10.76  0.00   1.00 -124.38


summary(lm0) #full

summary(lm1) #2
summary(lm4) #1
summary(lm4_reml) #1

```

#### Checking assumptions
```{r}
library(sjPlot)
plot_model(lm4_reml, type = "diag")

```


#### Plot results
```{r}
plot_model(lm4_reml, type = "est", show.intercept = T)
plot_model(lm4_reml, type = "eff")


```